
executable_file = chapter_2
c_file = /home/gihad/Documents/basic_of_pointers/examples/chapter_2/chapter_2.c


all:
	gcc -o $(executable_file) $(c_file) 

# run:	
	./$(executable_file)
	
# clean:	
	rm $(executable_file)


