
executable_file = chapter_6_2
c_file = /home/gihad/Documents/basic_of_pointers/examples/chapter_6_2/chapter_6_2.c


all:
	gcc -o $(executable_file) $(c_file) 

# run:	
	./$(executable_file)
	
# clean:	
	rm $(executable_file)


